#!/usr/bin/env bash

export QSG_RENDER_LOOP=basic
export QT_LOGGING_RULES="*.debug=true; qt.*.debug=false; qt.*.info=true; qt.qml.gc.allocatorStats=false; qt.qml.gc.statistics=false; qt.quick.focus=false; qt.quick.hover.trace=false; qt.qml.diskcache=false; qt.quick.dirty=false; qt.quick.itemview.lifecycle=false; qt.qml.binding.removal=false; qt.scenegraph.time.renderloop=false"
export QT_SCALE_FACTOR=2
export QSG_INFO=1


node engine/ohm.js 60600 &
node engine/ohm.js 54700 &
./ohmstudio
killall node
