#include <QObject>
#include <QString>
#include <QDebug>
#include <QThread>
#include <QIODevice>
#include <QJSValue>
#include <QList>
#include <QVariant>
#include <QQueue>
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QAudioOutput>
#include <QAudioInput>
#include <QAudioDeviceInfo>
#include <QFile>
#include <QDir>
#include <QDirIterator>
#include <QReadWriteLock>
#include <QWaitCondition>
#include <QQmlContext>
#include <QtConcurrent/QtConcurrentRun>
#include <QElapsedTimer>
#include <QQuickPaintedItem>
#include <QTimer>
#include <QPen>
#include <QPainter>
#include <QByteArray>
#include <cmath>
#include <cstdlib>
#include <functional>

#include "external/exprtk.hpp"
#include "external/RtMidi.h"
