#!/usr/bin/env bash


export QSG_RENDER_LOOP=threaded
export QT_LOGGING_RULES="*.debug=true; qt.*.debug=false"

node ohm.js 60600 &
node ohm.js 54700 &
QT_SCALE_FACTOR=4 qml -I . ohm/OhmStudio.qml
killall node
