#!/usr/bin/env bash


export QSG_RENDER_LOOP=basic
export QT_LOGGING_RULES="*.debug=true; qt.*.debug=false"
export QT_SCALE_FACTOR=2
export QT_QPA_PLATFORM=xcb
#export QSG_INFO=1

node ohm.js 60600 &
node ohm.js 54700 &
qmlscene --multisample --desktop -I . ohm/OhmStudio.qml
killall node
