#!/bin/bash

export EMDIR=~/emsdk
export QTDIR=~/qt/5.11.1/wasm/bin
export PATH=$QTDIR:$PATH
export QMAKE=$QTDIR/qmake

source $EMDIR/emsdk_env.sh

mkdir -p build/wasm
cd build/wasm
$QMAKE CONFIG+=release ../..
make clean
make -j20
cp ../../engine/ohm.js ../../engine/audio.js ../../engine/math.min.js .
cp ../../web/index.html ../../web/ohmblack.svg ../../web/favicon.ico .
npm install http-server
http-server -a localhost -c-1

