#!/bin/bash

export EMDIR=~/emsdk
export QTDIR=~/src/qtwasm/qtbase/bin
export PATH=$QTDIR:$PATH
export QMAKE=$QTDIR/qmake

source $EMDIR/emsdk_env.sh

mkdir -p build
cd build
$QMAKE CONFIG+=release ../..
make clean
make -j20
cd ..
cp index.html ohm.js audio.js math.min.js math.min.map ohmblack.png favicon.ico build/
./ohmserve
