language: node_js
node_js:
  - 6
  - 8
  - 10

# NAME env var is purely cosmetic, only way to identify builds until
# https://github.com/travis-ci/travis-ci/issues/5898 is fixed.

jobs:
  include:
    - stage: browser-tests
      node_js: 8
      script: npm run test:browser
      env: NAME=local browser
    - # second script to run in the browser-tests stage
      node_js: 8
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:browserstack; else true; fi'
      env: NAME=browserstack
